"""empty message

Revision ID: 6e08a27d0501
Revises: adbdc073eb15
Create Date: 2026-05-11 10:42:44.667247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e08a27d0501'
down_revision: Union[str, Sequence[str], None] = 'adbdc073eb15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transactions_coin_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_column('coins', 'id')
    
    op.add_column('coins', sa.Column('cg_id', sa.String(), nullable=False))
    op.create_primary_key('coins_pkey', 'coins', ['cg_id'])
    
    op.alter_column('transactions', 'coin_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    
    op.create_foreign_key(None, 'transactions', 'coins', ['coin_id'], ['cg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_coin_id_fkey'), 'transactions', 'coins', ['coin_id'], ['id'])
    op.alter_column('transactions', 'coin_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('coins', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('coins', 'cg_id')
    # ### end Alembic commands ###
