"""empty message

Revision ID: 9b27b177d6bb
Revises: 1d06fe7cdde5
Create Date: 2026-05-10 14:03:40.885507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b27b177d6bb'
down_revision: Union[str, Sequence[str], None] = '1d06fe7cdde5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coins', 'description')
    # ### end Alembic commands ###
